name: tt_bytepace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.1
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  http: ^1.2.1
  intl: ^0.19.0
  meta: ^1.11.0
  mockito: ^5.4.4
  path_provider: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
