name: tt_bytepace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  path: any
  get_it: ^7.6.7
  http: ^1.2.1
  intl: any
  meta: ^1.11.0
  mockito: ^5.4.4
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3
  equatable: ^2.0.5
  mask_text_input_formatter: ^2.9.0
  logger: ^2.2.0
  flutter_localizations:
    sdk: flutter
  talker_flutter: ^4.1.3
  talker_dio_logger: ^4.1.3
  talker_bloc_logger: ^4.1.3

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  path_provider_platform_interface: ^2.1.2
  flutter_lints: ^3.0.0
  test: ^1.24.9
  sqflite_common_ffi: ^2.3.3
  

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "lib/src/resources/assets//playstore-icon.png"
  image_path_ios: "lib/src/resources/assets//playstore-icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  # adaptive_icon_monochrome: "assets/images/icon-monochrome-432x432.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/src/resources/assets/
